# Generated by Django 5.1.3 on 2024-12-01 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'hospitals',
                'unique_together': {('hospital_id', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.TextField()),
                ('location', models.TextField()),
                ('department_name', models.TextField()),
                ('hospital_name', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_system_django.departments')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_system_django.hospitals')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='healthcare_system_django.hospitals'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('available_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthcare_system_django.doctors')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('doctor', 'available_date', 'available_time'), name='unique_doctor_slot')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='departments',
            unique_together={('department_id', 'hospital')},
        ),
    ]
