# Generated by Django 5.1.3 on 2024-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0002_departments_hospitals_doctors_departments_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='doctor_name',
            field=models.TextField(default='Unknown'),
        ),
    ]
