# Generated by Django 5.1.3 on 2024-12-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0003_doctoravailability_doctor_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'managed': False},
        ),
    ]
