# Generated by Django 5.1.3 on 2024-12-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0004_alter_doctoravailability_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctoravailability',
            table='doctor_availability',
        ),
    ]
