# Generated by Django 5.1.3 on 2024-12-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0005_alter_doctoravailability_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={},
        ),
    ]
