# Generated by Django 5.1.3 on 2024-12-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0007_alter_doctoravailability_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctor_name',
        ),
    ]
