# Generated by Django 5.1.3 on 2024-12-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_system_django', '0010_alter_doctoravailability_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'managed': False},
        ),
    ]
